### ISSUE TITLE
Does not work in 4.4

### ISSUE THREAD

**Issue by DesignedByLOC** [ndee85/Multi-Object-UV-Editing#14]
Python: Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 4.4\4.4\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 1499, in execute
    cmd_batch = self.exec_command_iter(is_modal)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\Blender Foundation\Blender 4.4\4.4\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2589, in exec_command_iter
    self.exec_legacy(source_filepath)
  File "C:\Program Files\Blender Foundation\Blender 4.4\4.4\scripts\addons_core\bl_pkg\bl_extension_ops.py", line 2722, in exec_legacy
    bpy.types.PREFERENCES_OT_addon_install.execute(self, bpy.context)
  File "C:\Program Files\Blender Foundation\Blender 4.4\4.4\scripts\startup\bl_operators\userpref.py", line 813, in execute
    bpy.ops.preferences.addon_enable(module=mod.__name__)
  File "C:\Program Files\Blender Foundation\Blender 4.4\4.4\scripts\modules\bpy\ops.py", line 109, in __call__
    ret = _op_call(self.idname_py(), kw)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Error: 'module' object has no attribute 'VIEW3D_PT_tools_object'
'module' object has no attribute 'VIEW3D_PT_tools_object'
